-- Code generated by foundation webhook; DO NOT EDIT.
-- webhook-schema-version: 1
-- webhook-schema-digest: 9803a04dd7f5bfa42c4def6c63ed6a684bbd9f482d87e499987797a8c36e529e

DROP TABLE IF EXISTS webhook_replay_receipts;
DROP TABLE IF EXISTS webhook_inbound_receipts;
DROP TABLE IF EXISTS webhook_attempts;
DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhook_events;
DROP TABLE IF EXISTS webhook_subscription_revisions;
DROP TABLE IF EXISTS webhook_subscriptions;
DROP TABLE IF EXISTS webhook_endpoint_revisions;
DROP TABLE IF EXISTS webhook_endpoints;
DROP TABLE IF EXISTS webhook_secret_material;
DROP TABLE IF EXISTS webhook_instances;
