-- Code generated by foundation webhook; DO NOT EDIT.
-- webhook-schema-version: 1
-- webhook-schema-digest: 9803a04dd7f5bfa42c4def6c63ed6a684bbd9f482d87e499987797a8c36e529e

CREATE TABLE webhook_instances (
    instance_key TEXT PRIMARY KEY,
    schema_version BIGINT NOT NULL,
    catalog_version BIGINT NOT NULL,
    catalog_digest TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE webhook_secret_material (
    instance_key TEXT NOT NULL REFERENCES webhook_instances(instance_key) ON DELETE CASCADE,
    secret_ref TEXT NOT NULL,
    revision TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('primary','previous')),
    nonce BYTEA NOT NULL,
    ciphertext BYTEA NOT NULL,
    not_before TIMESTAMPTZ NOT NULL,
    not_after TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, secret_ref, revision)
);

CREATE UNIQUE INDEX webhook_secret_primary_idx
    ON webhook_secret_material(instance_key, secret_ref)
    WHERE role = 'primary';

CREATE TABLE webhook_endpoints (
    instance_key TEXT NOT NULL REFERENCES webhook_instances(instance_key) ON DELETE CASCADE,
    endpoint_id TEXT NOT NULL,
    current_revision BIGINT NOT NULL,
    current_state TEXT NOT NULL CHECK (current_state IN ('active','paused','disabled','revoked')),
    secret_ref TEXT NOT NULL,
    etag TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, endpoint_id)
);

CREATE TABLE webhook_endpoint_revisions (
    instance_key TEXT NOT NULL,
    endpoint_id TEXT NOT NULL,
    revision BIGINT NOT NULL,
    target_url TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    state TEXT NOT NULL,
    etag TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, endpoint_id, revision),
    FOREIGN KEY (instance_key, endpoint_id)
        REFERENCES webhook_endpoints(instance_key, endpoint_id) ON DELETE CASCADE
);

CREATE TABLE webhook_subscriptions (
    instance_key TEXT NOT NULL REFERENCES webhook_instances(instance_key) ON DELETE CASCADE,
    subscription_id TEXT NOT NULL,
    endpoint_id TEXT NOT NULL,
    current_revision BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL,
    etag TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, subscription_id),
    FOREIGN KEY (instance_key, endpoint_id)
        REFERENCES webhook_endpoints(instance_key, endpoint_id)
);

CREATE TABLE webhook_subscription_revisions (
    instance_key TEXT NOT NULL,
    subscription_id TEXT NOT NULL,
    revision BIGINT NOT NULL,
    endpoint_id TEXT NOT NULL,
    event_types JSONB NOT NULL,
    enabled BOOLEAN NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    etag TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, subscription_id, revision),
    FOREIGN KEY (instance_key, subscription_id)
        REFERENCES webhook_subscriptions(instance_key, subscription_id) ON DELETE CASCADE
);

CREATE INDEX webhook_subscriptions_endpoint_idx
    ON webhook_subscriptions(instance_key, endpoint_id, enabled);

CREATE TABLE webhook_events (
    instance_key TEXT NOT NULL REFERENCES webhook_instances(instance_key) ON DELETE CASCADE,
    event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    subject TEXT NOT NULL DEFAULT '',
    raw_body BYTEA NOT NULL,
    body_digest TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    command_fingerprint TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    published_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, event_id),
    UNIQUE (instance_key, idempotency_key)
);

CREATE INDEX webhook_events_type_time_idx
    ON webhook_events(instance_key, event_type, published_at DESC, event_id);

CREATE TABLE webhook_deliveries (
    instance_key TEXT NOT NULL,
    delivery_id TEXT NOT NULL,
    event_id TEXT NOT NULL,
    endpoint_id TEXT NOT NULL,
    endpoint_revision BIGINT NOT NULL,
    subscription_id TEXT NOT NULL,
    subscription_revision BIGINT NOT NULL,
    state TEXT NOT NULL CHECK (state IN ('pending','delivering','retrying','delivered','failed','paused','cancelled')),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ,
    last_error_code TEXT NOT NULL DEFAULT '',
    replay_of TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, delivery_id),
    FOREIGN KEY (instance_key, event_id)
        REFERENCES webhook_events(instance_key, event_id) ON DELETE RESTRICT,
    FOREIGN KEY (instance_key, endpoint_id, endpoint_revision)
        REFERENCES webhook_endpoint_revisions(instance_key, endpoint_id, revision),
    FOREIGN KEY (instance_key, subscription_id, subscription_revision)
        REFERENCES webhook_subscription_revisions(instance_key, subscription_id, revision)
);

CREATE INDEX webhook_deliveries_due_idx
    ON webhook_deliveries(instance_key, state, next_attempt_at, delivery_id);
CREATE INDEX webhook_deliveries_endpoint_idx
    ON webhook_deliveries(instance_key, endpoint_id, created_at DESC, delivery_id);

CREATE TABLE webhook_attempts (
    instance_key TEXT NOT NULL,
    attempt_id TEXT NOT NULL,
    delivery_id TEXT NOT NULL,
    attempt_number INTEGER NOT NULL,
    outcome TEXT NOT NULL,
    status_code INTEGER NOT NULL DEFAULT 0,
    error_code TEXT NOT NULL DEFAULT '',
    request_digest TEXT NOT NULL,
    response_digest TEXT NOT NULL DEFAULT '',
    secret_revision TEXT NOT NULL DEFAULT '',
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    PRIMARY KEY (instance_key, attempt_id),
    UNIQUE (instance_key, delivery_id, attempt_number),
    FOREIGN KEY (instance_key, delivery_id)
        REFERENCES webhook_deliveries(instance_key, delivery_id) ON DELETE CASCADE
);

CREATE TABLE webhook_inbound_receipts (
    instance_key TEXT NOT NULL REFERENCES webhook_instances(instance_key) ON DELETE CASCADE,
    receipt_id TEXT NOT NULL,
    inbound_source TEXT NOT NULL,
    event_id TEXT NOT NULL,
    body_digest TEXT NOT NULL,
    secret_revision TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL,
    accepted_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, receipt_id),
    UNIQUE (instance_key, inbound_source, event_id)
);

CREATE TABLE webhook_replay_receipts (
    instance_key TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    original_delivery_id TEXT NOT NULL,
    replay_delivery_id TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (instance_key, idempotency_key),
    FOREIGN KEY (instance_key, original_delivery_id)
        REFERENCES webhook_deliveries(instance_key, delivery_id),
    FOREIGN KEY (instance_key, replay_delivery_id)
        REFERENCES webhook_deliveries(instance_key, delivery_id)
);
