// Code generated by foundation httpcontract; DO NOT EDIT.

package galleryerr

import (
	"sort"

	"github.com/yueli-official/foundation/go/problem"
)

const (
	CodeAbuseReplay              = "gallery.abuse_attempt_replayed"
	CodeAbuseUnavailable         = "gallery.abuse_unavailable"
	CodeAuthorizationUnavailable = "gallery.authorization_unavailable"
	CodeChallengeRequired        = "gallery.challenge_required"
	CodeConflict                 = "gallery.conflict"
	CodeForbidden                = "gallery.forbidden"
	CodeGatewayTimeout           = "gallery.gateway.timeout"
	CodeGatewayUnavailable       = "gallery.gateway.unavailable"
	CodeGone                     = "gallery.gone"
	CodeInvalidState             = "gallery.invalid_state"
	CodeUnauthorized             = "gallery.not_authenticated"
	CodeNotFound                 = "gallery.not_found"
	CodeNotInitialized           = "gallery.not_initialized"
	CodeRateLimited              = "gallery.rate_limited"
	CodeBodyTooLarge             = "gallery.request.body_too_large"
	CodeRequestInvalid           = "gallery.request.invalid"
	CodeMethodNotAllowed         = "gallery.request.method_not_allowed"
	CodeUpstreamFailed           = "gallery.upstream_failed"
)

var descriptors = map[string]problem.Descriptor{
	CodeAbuseReplay:              descriptor(CodeAbuseReplay, 409),
	CodeAbuseUnavailable:         descriptor(CodeAbuseUnavailable, 503),
	CodeAuthorizationUnavailable: descriptor(CodeAuthorizationUnavailable, 503),
	CodeChallengeRequired:        descriptor(CodeChallengeRequired, 403),
	CodeConflict:                 descriptor(CodeConflict, 409),
	CodeForbidden:                descriptor(CodeForbidden, 403),
	CodeGatewayTimeout:           descriptor(CodeGatewayTimeout, 504),
	CodeGatewayUnavailable:       descriptor(CodeGatewayUnavailable, 502),
	CodeGone:                     descriptor(CodeGone, 410),
	CodeInvalidState:             descriptor(CodeInvalidState, 409),
	CodeUnauthorized:             descriptor(CodeUnauthorized, 401),
	CodeNotFound:                 descriptor(CodeNotFound, 404),
	CodeNotInitialized:           descriptor(CodeNotInitialized, 503),
	CodeRateLimited:              descriptor(CodeRateLimited, 429),
	CodeBodyTooLarge:             descriptor(CodeBodyTooLarge, 413),
	CodeRequestInvalid:           descriptor(CodeRequestInvalid, 400),
	CodeMethodNotAllowed:         descriptor(CodeMethodNotAllowed, 405),
	CodeUpstreamFailed:           descriptor(CodeUpstreamFailed, 502),
}

func descriptor(code string, status int) problem.Descriptor {
	return problem.MustDescriptor(problem.MustKind(code, status), "https://errors.yueli.dev/problems/"+code)
}

func DescriptorForCode(code string) (problem.Descriptor, bool) {
	value, ok := descriptors[code]
	return value, ok
}

type CatalogEntry struct {
	Code   string `json:"code"`
	Status int    `json:"status"`
}

func Catalog() []CatalogEntry {
	result := make([]CatalogEntry, 0, len(descriptors))
	for code, value := range descriptors {
		result = append(result, CatalogEntry{Code: code, Status: value.Kind().Status()})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Code < result[j].Code })
	return result
}
